name: Python testing

on:
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed]

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
    - name: Check workflow result
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
          echo "Python tests failed"
          exit 1
        fi
        echo "Python tests passed"